# Generated by Django 4.2.5 on 2023-09-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lamps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddressV4', models.CharField(max_length=15)),
                ('macaddress', models.CharField(max_length=12)),
            ],
        ),
    ]
